[package]
name = "chat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.78"
chrono = "0.4.31"
clap = {version = "4.4.12", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.25.0"
