name: Rust checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    name: Run check, test and lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install components
        shell: bash
        run: rustup component add clippy rustfmt; apt install screen -y

      - name: Run format checks
        shell: bash
        run: cargo fmt --all --check

      - name: Run linter
        shell: bash
        run: cargo clippy
      
      - name: Run server in background and wait for it to start
        shell: bash
        run: screen -d -m cargo run -p chat_server -xS chat_server; sleep 2

      - name: Run tests
        shell: bash
        run: cargo test

# You can also use dedicated actions:
# - https://github.com/actions-rs (popular, but abandoned recently)
# - https://github.com/actions-rust-lang
# - https://github.com/Cardinal-Cryptography/github-actions/blob/main/install-rust-toolchain/action.yml
